# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks

# The "main" locale.
base_locale: en

## Reporting locale, default: en. Available: en, ru.
# internal_locale: en

# Read and write translations.
data:
  ## Translations are read from the file system. Supported format: YAML, JSON.
  ## Provide a custom adapter:
  # adapter: I18n::Tasks::Data::FileSystem

  # Locale files or `File.find` patterns where translations are read from:
  read:
    - config/locales/%{locale}.yml

  # Locale files to write new keys to, based on a list of key pattern => file rules. Matched from top to bottom:
  # `i18n-tasks normalize -p` will force move the keys according to these rules
  write:
    - config/locales/%{locale}.yml

  ## Specify the router (see Readme for details). Valid values: conservative_router, pattern_router, or a custom class.
  # router: convervative_router

  yaml:
    write:
      # do not wrap lines at 80 characters
      line_width: -1

  ## Pretty-print JSON:
  # json:
  #   write:
  #     indent: '  '
  #     space: ' '
  #     object_nl: "\n"
  #     array_nl: "\n"

# Find translate calls
search:
  ## Paths or `File.find` patterns to search in:
  paths:
    - app
    - lib

  # Root directories for relative keys resolution.
  relative_roots:
    - app/controllers
    - app/helpers
    - app/mailers
    - app/presenters
    - app/services
    - app/views
    - app/cells

  ## Files or `File.fnmatch` patterns to exclude from search. Some files are always excluded regardless of this setting:
  ##   %w(*.jpg *.png *.gif *.svg *.ico *.eot *.otf *.ttf *.woff *.woff2 *.pdf *.css *.sass *.scss *.less *.yml *.json)
  exclude:
    - "*.jpeg"
    - "*.odt"
    - "*.docx"

  ## Alternatively, the only files or `File.fnmatch patterns` to search in `paths`:
  ## If specified, this settings takes priority over `exclude`, but `exclude` still applies.
  # only: ["*.rb", "*.html.slim"]

  ## If `strict` is `false`, guess usages such as t("categories.#{category}.title"). The default is `true`.
  strict: false

  ## Multiple scanners can be used. Their results are merged.
  ## The options specified above are passed down to each scanner. Per-scanner options can be specified as well.
  ## See this example of a custom scanner: https://github.com/glebm/i18n-tasks/wiki/A-custom-scanner-example

## Google Translate
# translation:
#   # Get an API key and set billing info at https://code.google.com/apis/console to use Google Translate
#   api_key: "AbC-dEf5"

translation:
  deepl_api_key: <%= ENV["DEEPL_API_KEY"] %>

# Do not consider these keys missing:
ignore_missing:
 - faker.*
 - activemodel.attributes.common.created_at
 - decidim.endorsable.endorsements_count
 - decidim.endorsable.endorsements
 - decidim.proposals.proposals.votes_count.most_popular_proposal
 - decidim.proposals.proposals.votes_count.need_more_votes
 - layouts.decidim.participatory_processes.promoted_process_group.more_info
 - decidim.proposals.proposals.preview.update_position
 - decidim.meetings.withdraw.success
 - decidim.meetings.withdraw.error
 - decidim.account.show.available_locales_helper
 - decidim.initiatives.admin.initiatives_types.form.title
 - decidim.initiatives.admin.initiatives_types.form.options
 - decidim.initiatives.admin.initiatives_types.form.child_scope_threshold_enabled_help
 - decidim.initiatives.admin.initiatives_types.form.only_global_scope_enabled_help
 - decidim.initiatives.admin.initiatives_types.form.authorizations
 - decidim.initiatives.initiatives.show.any_vote_method
 - decidim.initiatives.initiatives.show.offline_method
 - decidim.initiatives.initiatives.show.edit
 - decidim.initiatives.initiatives.show.send_to_technical_validation
 - decidim.initiatives.initiatives.show.confirm
 - decidim.initiatives.initiatives.show.print
 - decidim.initiatives.initiatives.show.follow_description
 - layouts.decidim.footer.cc_by_license
 - layouts.decidim.footer.decidim_logo
 - layouts.decidim.social_media_links.twitter
 - layouts.decidim.social_media_links.facebook
 - layouts.decidim.social_media_links.instagram
 - layouts.decidim.social_media_links.youtube
 - layouts.decidim.social_media_links.github
 - layouts.decidim.header.user_menu
 - decidim.admin.initiatives_settings.update.success
 - decidim.admin.initiatives_settings.update.error
 - decidim.initiatives.admin.initiatives.edit.success
 - decidim.initiatives.admin.initiatives_settings.update.settings
 - decidim.initiatives.update.success
 - decidim.initiatives.update.error
 - decidim.initiatives.initiatives.vote_cabin.supports_required
 - decidim.initiatives.initiatives.index_header.new_initiative
 - decidim.initiatives.initiatives.index_header.not_authorized.{title,close,explanation,authorizations_page}
 - decidim.initiatives.create_initiative.fill_data.{back,fill_data_help,more_information,initiative_type,select_scope,select_area,continue}
 - decidim.initiatives.create_initiative.select_initiative_type.{back,select_initiative_type_help,more_information,choose_html.select}
 - decidim.initiatives.form.attachment_legend
 - decidim.initiatives.form.add_attachments
 - decidim.resources.admin.initiatives_settings.edit.update
 - decidim.resources.admin.initiatives_settings.form.{comments,date,publication_date,random,signatures,title}
 - decidim.resources.admin_log.initiatives_settings.update
 - decidim.initiatives.admin.initiatives_settings.update.success
 - decidim.initiatives.create_initiative.select_initiative_type.{choose_html,select}
 - decidim.initiatives.admin.initiatives_settings.form.*
 - decidim.initiatives.admin.initiatives_settings.edit.update
 - decidim.initiatives.signature_interval.title
 - decidim.initiatives.admin_log.initiatives_settings.update
 - decidim.initiatives.form.delete_attachment
 - decidim.budgets.admin.budgets.index.paper_ballots
 - decidim.budgets.admin.imports.help.paper_ballot_results
 - decidim.budgets.admin.imports.label.paper_ballot_results
 - decidim.budgets.admin.imports.title.paper_ballot_results
 - decidim.editor_images.create.*
 - decidim.admin.actions.import
 - decidim.budgets.admin.projects.index.*
 - decidim.budgets.admin.models.project.name
 - decidim.budgets.admin.imports.resources.paper_ballot_results
 - decidim.budgets.actions.*
 - decidim.budgets.actions.confirm_destroy
 - decidim.budgets.models.project.fields.*
 - decidim.budgets_importer.actions.import
 - index.confirmed_orders_count
 - activemodel.errors.models.user.attributes.password.password_blank

# Consider these keys used:
ignore_unused:
  - faker.*
  - activemodel.attributes.osp_authorization_handler.*
  - activemodel.attributes.participatory_process.private_space
  - decidim.accessibility.skip_button
  - decidim.authorization_handlers.osp_authorization_handler.*
  - decidim.authorization_handlers.osp_authorization_workflow.*
  - decidim.components.proposals.settings.global.*
  - decidim.proposals.proposals.form_view.cancel
  - decidim.verifications.authorizations.first_login.actions.osp_authorization_handler
  - decidim.verifications.authorizations.first_login.actions.osp_authorization_workflow
  - activemodel.attributes.participatory_process.private_space
  - decidim.amendments.emendation.announcement.evaluating
  - forms.length_validator.minimum.*
  - decidim.events.budgets.pending_order.*
  - layouts.decidim.user_menu.account
  - activemodel.attributes.initiatives_type.comments_enabled
  - decidim.newsletter_mailer.newsletter.{note,unsubscribe}
  - decidim.proposals.proposals.preview.update_position
  - decidim.initiatives.create_initiative.select_initiative_type.*
  - decidim.admin.menu.initiatives_settings
  - decidim.initiatives.admin.initiatives_settings.update.settings
  - decidim.resources.admin.initiatives_settings.edit.update
  - decidim.resources.admin.initiatives_settings.form.*
  - decidim.resources.admin_log.initiatives_settings.update
  - decidim.resources.initiatives_type.actions.create
  - decidim.resources.signature_interval.title
  - decidim.initiatives.admin.initiatives_settings.update.success
  - decidim.initiatives.admin_log.initiatives_settings.update
  - activemodel.attributes.initiative.area_id
  - decidim.authorization_handlers.data_authorization_handler.*
  - decidim.meetings.directory.meetings.index.all
  - decidim.meetings.meeting.not_allowed
  - decidim.meetings.meetings.create.*
  - decidim.meetings.meetings.update.*
  - decidim.budgets.admin.budgets.index.paper_ballots
  - decidim.budgets.admin.imports.help.paper_ballot_results
  - decidim.budgets.admin.imports.label.paper_ballot_results
  - decidim.budgets.admin.imports.title.paper_ballot_results
  - activemodel.errors.models.user.attributes.password.password_blank
  - rack_attack.too_many_requests.{message,time,time_unit,title}
  - decidim.budgets.admin.imports.resources.paper_ballot_results
